README.md
cmd/helper.go
cmd/root.go
internal/app/exporter/exporter.go

Add AWS account ID and region labels
AWS customers may have RDS instances with the same name in different AWS accounts or/and regions.
When a single Prometheus deployment collects metrics for different it may lead to conflict.
- Add `aws_account_id` and `aws_region` labels
- Document metrics's labels in the README

Add AWS session information labels

---

README.md
internal/app/exporter/exporter.go

Rename rds_instance_maxIops_average to rds_instance_max_iops_average
Have consistency in metrics name
Rename `rds_instance_maxIops_average` to `rds_instance_max_iops_average`

Rename rds_instance_maxIops_average to rds_instance_max_iops_average

---

configs/helm/templates/_helpers.tpl

Add well-known Kubernetes labels
Facilitate Kubernetes audit and use standard configuration.
See https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels
- Add `app.kubernetes.io/name`, `app.kubernetes.io/component` and `app.kubernetes.io/part-of`

Add well-known Kubernetes labels

---

.markdownlint.yaml
.pre-commit-config.yaml
CONTRIBUTING.md
README.md
cmd/helper.go
cmd/root.go
internal/app/exporter/exporter.go
scripts/prometheus/docker-compose.yml

Fix aws labels and few improvements
aws_region and aws_account_id are incorrect on instance type metrics
- Fix incorrect instance type labels
- Add Markdown linter
- Use JSON log format by default

Fix region and linter

---

README.md
internal/app/exporter/exporter.go
internal/app/rds/rds.go

Avoid crashes when performance insight is not enabled.
In some circumstances, performance insight returns an empty value.
See https://github.com/qonto/prometheus-rds-exporter/issues/10
- Handle performance insight empty value
- Add `performance_insights_enabled` label in `rds_instance_info`

Fix performance insights metric

---

configs/helm/templates/servicemonitor.yaml
configs/helm/tests/servicemonitor_test.yaml
configs/helm/tests/values/with_servicemonitor.yaml
configs/helm/values.yaml

Add Servicemonitor parameter
Allow service monitor customization, see https://github.com/qonto/prometheus-rds-exporter/issues/13
- Add `externalLabels`, `metricRelabelings`, `relabelings`, `sampleLimit`, and `scrapeTimeout` parameters

Add Servicemonitor parameters

---

README.md

Fix Grafana's broken links
When a dashboard is renamed on Grafana.com it changes the URL of the page and leads to a 404 error.
Grafana automatically redirects if we use only the dashboard ID, so it's more future-proof if we want to change dashboard names.
Example
```
curl -s -w "Code: %{response_code}\nRedirect: %header{location}\n"  https://grafana.com/grafana/dashboards/19646/any-name -o /dev/null
Code: 404
Redirect: 
```
```
curl -s -w "Code: %{response_code}\nRedirect: %header{location}\n"  https://grafana.com/grafana/dashboards/19646/ -o /dev/null
Code: 301
Redirect: /grafana/dashboards/19646-rds-instance-details/
````
- Do not specify dashboard names in URL

Fix Grafana broken links

---

internal/app/rds/rds.go
internal/app/rds/rds_test.go

Consider unapplied parameter groups as pending modified values
An RDS instance should be considered as "pending modified values" when instance modifications are pending (current behavior) but also when parameter groups are unapplied.
It's common to see RDS instances running with pending parameter group in "pending-reboot" status. It's tricky to detect it from AWS RDS console because this information is only displayed in the configuration tab of each RDS instance.
<details>
<summary>Example</summary>
No maintenance on RDS instances list
Parameter group are not applied
</details>
- Add unapplied parameter group as condition to mark instance with "pending modified values"

Consider unapplied parameter groups as pending modified values

---

.goreleaser.yaml

The link was wrong, pointing to a non-existing project.

fix(doc): Update .goreleaser.yaml: fix link to full changelog

---

.gitignore
README.md
cmd/root.go
configs/prometheus-rds-exporter/prometheus-rds-exporter.yaml
internal/infra/http/index.go
internal/infra/http/server.go

Facilitate settings
Using a hidden file configuration (.prometheus-rds-exporter.yaml) is not relevant for a service and should be fixed.
- **Breaking change** Use `prometheus-rds-exporter.yaml` instead of `.prometheus-rds-exporter.yaml`
- Document all exporter settings (including the Debian package)
- Fix incorrect parameter in the README

Settings improvement

---

README.md
internal/app/exporter/exporter.go
internal/app/rds/rds.go
internal/app/rds/rds_test.go

- The CA identifier is exposed as `ca_certificate_identifier` attribute of the `rds_instance_info` metric
- The Unix timestamp of the expiration date of the CA certificate is exposed in the `rds_ca_certificate_valid_until` gauge.
For the `rds-ca-2019` RDS CA, values are:
```
rds_instance_info{aws_account_id="012345678901",aws_region="eu-west-1",ca_certificate_identifier="rds-ca-2019",dbidentifier="rds-1",...}
rds_ca_certificate_valid_until{aws_account_id="012345678901",aws_region="eu-west-1",dbidentifier="rds-1"} 1.72434653e+09
```

chore(metrics): Export RDS Certificate Authority attributes

---

README.md
docs/add-metric.md
internal/app/exporter/exporter.go
internal/app/rds/rds.go
internal/app/rds/rds_test.go

Add instance age metric
Some workloads require raising alerts based on instance age.
At Qonto, we raise alerts when some instances (based on name patterns) run too long to prevent uncontrolled AWS costs.
- Add `rds_instance_age_seconds`
- Document how to add a new metric

Add instance age metric

---

README.md
internal/app/cloudwatch/usage.go
internal/app/cloudwatch/usage_test.go
internal/app/exporter/exporter.go
internal/app/rds/rds.go
internal/app/rds/rds_test.go
internal/app/servicequotas/servicequotas.go
internal/app/servicequotas/servicequotas_test.go
internal/app/unit/converter.go
internal/app/unit/converter_test.go

Specify units for `rds_replication_slot_disk_usage_average` and `rds_usage_allocated_storage_average`
According to [Prometheus metrics best practices](https://prometheus.io/docs/practices/naming/), these metrics should contain the `_bytes` suffix instead of `_average`
`rds_usage_allocated_storage_average` was specified in Gigabytes while it should be in Bytes.
- Rename `rds_replication_slot_disk_usage_average` to `rds_replication_slot_disk_usage_bytes`
- Rename `rds_usage_allocated_storage_average` to `rds_usage_allocated_storage_bytes`
Issue was reported by end-user in https://github.com/qonto/prometheus-rds-exporter/issues/32

Rename metrics without units

---

scripts/prometheus/configuration/grafana/entrypoint.sh

Add Golang dashboard
The [Go Runtime Exporter Quickstart and Dashboardby Grafana Labs dashboard](https://grafana.com/grafana/dashboards/14061-go-runtime-metrics/) is helpful to visualize Golang internal metrics.
It was helpful to investigate https://github.com/qonto/prometheus-rds-exporter/pull/41
- Add Go dashboard to local development environment

Add Golang dashboard

---

scripts/prometheus/docker-compose.yml

Upgrade Grafana & Prometheus to the latest versions
It was helpful to use the latest versions to investigate the dashboard releasing issue for [Grafana's case 114605](https://grafana.com/orgs/qonto/tickets/114605).
No major changes or breaking changes in Grafana [10.1.0](https://github.com/grafana/grafana/releases/tag/v10.1.0), [10.2.0](https://github.com/grafana/grafana/releases/tag/v10.2.0) or Prometheus [2.46.0](https://github.com/prometheus/prometheus/releases/tag/v2.46.0), [2.47.0](https://github.com/prometheus/prometheus/releases/tag/v2.47.0) and  [2.48.0](https://github.com/prometheus/prometheus/releases/tag/v2.48.0)
- Upgrade `Grafana` to `10.2.2`
- Upgrade `Prometheus` to `2.48.0`

Upgrade Grafana & Prometheus

---

README.md

This label has been introduced in https://github.com/qonto/prometheus-rds-exporter/pull/38 , but README.md has not been updated with this new label

chore(doc): Add missing ca_certificate_identifier label in rds_instance_info metric in README description

---

README.md
internal/app/exporter/exporter.go
internal/app/rds/rds.go
internal/app/rds/rds_test.go

Add `arn` label to `rds_instance_info` metric.
ARN information is the uniq identifier for RDS instance.
This information could be used for alerting
Add `arn` label to `rds_instance_info` metric.

Add arn label to rds_instance_info metric

---

README.md
cmd/root.go
configs/prometheus-rds-exporter/prometheus-rds-exporter.yaml
internal/app/exporter/exporter.go
internal/app/rds/rds.go
internal/app/rds/rds_test.go

Add `aws_instance_tags` containing AWS tags attached to the instance.
We received a feature request to have AWS tags in https://github.com/qonto/prometheus-rds-exporter/issues/37.
Implementation is similar to [yet-another-cloudwatch-exporter](https://github.com/nerdswords/yet-another-cloudwatch-exporter/tree/master#query-examples-without-exportedtagsonmetrics). To limit cardinality, the tags are published in  `rds_instance_tags` metric.
The metrics looks like:
```
rds_instance_tags{aws_account_id="<account_id>",aws_region="<aws_region>",dbidentifier="<rds_identifier>",tag_Tag1="value1",tag_Tag2="value2"} 0
```
So it could be used to join metrics:
```
max by (aws_account_id, aws_region, dbidentifier) (rds_free_storage_bytes{} * 100 / rds_allocated_storage_bytes{}) + on (aws_account_id, …
```

Add aws_instance_tags containing AWS tags attached to the instance

---

scripts/prometheus/docker-compose.yml

Enable Prometheus lifecycle API
Facilitate local development
We can reload Prometheus configuration with simple curl command
```bash
curl -X POST localhost:9090/-/reload
```
- Enable Prometheus lifecycle API

Enable Prometheus lifecycle API

---

README.md
configs/aws/policy.json
configs/terraform/main.tf

Use more restrictive IAM policy
Help AWS users to audit and adjust IAM permissions to enable features.
For instance, it will be easier for users who don't collect log information (`collect-logs-size=false`) to remove unnecessary IAM permissions.
Today, we don't specify parameters to collect AWS RDS maintenances, so we can't limit `resource` for `rds:DescribePendingMaintenanceActions` action, but we may support in the future.
- Update IAM policies
- Fix typo in README

Use more restrictive IAM policy

---

README.md
cmd/root.go
configs/prometheus-rds-exporter/prometheus-rds-exporter.yaml
docs/add-configuration-parameter.md
internal/infra/http/server.go

Add support of TLS
A Qonto partner has requested that metrics be exposed via HTTPS in https://github.com/qonto/prometheus-rds-exporter/issues/110
- Add `tls-cert-path` and `tls-key-path` parameters

Add support of TLS

---

internal/infra/http/homepage.go

Ignore false postive alert for homepage
Semgrep is reporting `go.lang.security.audit.xss.no-direct-write-to-responsewriter.no-direct-write-to-responsewriter` alert:
```
┌────────────────┐
│ 1 Code Finding │
└────────────────┘
internal/infra/http/homepage.go 
❯❱ go.lang.security.audit.xss.no-direct-write-to-responsewriter.no-direct-write-to-responsewriter
Detected directly writing or similar in 'http.ResponseWriter.write()'. This bypasses HTML escaping
that prevents cross-site scripting vulnerabilities. Instead, use the 'html/template' package and  
render data using 'template.Execute()'.                                                           
Details: https://sg.run/EkbA                                                                      
56┆ _, _ = w.Write(h.content)
```
We fixed it …

Ignore false postive alert for homepage

---

internal/app/rds/helper.go
internal/app/rds/rds.go
internal/app/rds/rds_test.go

Support for io2 storage type
Amazon RDS now supports io2 Block Express, but Prometheus RDS exporter don't [support it](https://github.com/qonto/prometheus-rds-exporter/blob/ac1a3e5c5f5d786cb3c0f97d83e00faded038d0e/internal/app/rds/helper.go#L41-L93) yet.
Similar to existing storage class types, the information **is not accurate** since we are not evaluating engine database and nitro instance type. **This will be a requirement to release v1 of Prometheus RDS exporter.**
> <img width="783" alt="screenshot 2024-03-12 at 23 25 10" src="https://github.com/qonto/prometheus-rds-exporter/assets/319005/0dffaa9a-6d3d-49af-8d96-f991c50f55f1">
> https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html
> ![io2_bx](https://github.com/qonto/prometheus-rds-exporter/assets/319005/42649988-1 …

Support for io2 storage type

---

internal/app/exporter/helper.go
internal/app/exporter/helper_test.go

Avoid crash when the RDS instance contains tags with unsupported label characters
End-user reported exporter crash when an RDS contains unsupported label characters ( https://github.com/qonto/prometheus-rds-exporter/issues/120).
The `ClearPrometheusLabel()` was not sanitizing correctly the tag.
> Metric names may contain ASCII letters, digits, underscores, and colons. It must match the regex [a-zA-Z_:][a-zA-Z0-9_:]*.
> https://prometheus.io/docs/concepts/data_model/
- Fixed `ClearPrometheusLabel()` function to remove unsupported characters from the Prometheus label

Avoid crash when the RDS instance contains tags with unsupported label characters

---

internal/app/ec2/ec2.go

Avoid crash when metrics does not exists
RDS exporter could crash when some EC2 information are empty.
It could occured for instances without EBS optimization or invalid state 
- Handle empty nil pointer in `EC2` package (AWS SDK built-in method)

Avoid crash when metrics does not exists

---

.github/dependabot.yml

Group OpenTelemetry automatic merge requests
OpenTelemetry package is frequently updated, which lead dependabot to open many Merge requests.
It require more reviews than it should.
- Group OpenTelemetry automatic merge requests

Group OpenTelemetry automatic merge requests

---

internal/app/ec2/ec2.go
internal/app/ec2/ec2_test.go
internal/app/ec2/mock/ec2.go

Fix crash when polling EC2 instance without EBS optimized storage
The https://github.com/qonto/prometheus-rds-exporter/issues/141 bug was partially fixed by https://github.com/qonto/prometheus-rds-exporter/pull/152.
The `EbsInfo.EbsOptimizedInfo` could be a nil pointer as well as `EbsInfo` when an EC2 instance don't have EBS optimization information. So we need to check this value before using it.
- Refact EC2 tests to use table test approach (Golang standard)
- Add tests for EC2 instance without EBS optimization (t2.small)
- Check nil value for `VCpuInfo`, `MemoryInfo`, `EbsInfo` and `EbsInfo.EbsOptimizedInfo` nil pointer

Fix crash on ec2 type missing info

---

README.md
configs/helm/grafana_dashboards
configs/helm/templates/grafanadashboard.yaml
configs/helm/tests/grafanadashboard_test.yaml
configs/helm/tests/servicemonitor_test.yaml
configs/helm/tests/values/with_grafanadashboards.yaml
configs/helm/tests/values/without_grafanadashboards.yaml
configs/helm/values.yaml
scripts/kubeconform-test.sh
scripts/kubeconform/grafana.integreatly.org/README.md
scripts/kubeconform/grafana.integreatly.org/grafanadashboard_v1beta1.json

Add Grafana dashboard CRD
To ensure an optimal user experience, it is essential to regularly update our dashboards. This practice guarantees that end-users are always working with the latest features and improvements, enabling them to make the most out of the data presented to helm. However, maintaining multiple versions of dashboards can be challenging and is not desirable. It introduces complexity and can lead to inconsistencies between what they see and the actual data.
Grafana labs is very convient to make our project visible, but lack of documented API prevent dashboard automation, and lack of automation on Grafana itself prevent keeping dashboards up-to-date.
This is where our decision to utilize the Grafana Operator comes into play. By leveraging the Grafana Operator, we can rest …

Add Grafana dashboard CRD

---

README.md
configs/helm/tests/grafanadashboard_test.yaml
configs/helm/tests/values/with_grafanadashboards.yaml
configs/helm/tests/values/with_grafanadashboards_custom.yaml
configs/helm/tests/values/without_grafanadashboards.yaml
configs/helm/values.yaml

Disable automatic dashboard deployment
Dashboards deployment should be opt-in because deployment could be blocked if Grafana CRD does not exist.
- Set `enabled: true`

Disable automatic dashboard deployment

---

README.md
configs/grafana/panels/instance.libsonnet
configs/grafana/public/rds-instance.json
configs/grafana/queries/instance.libsonnet
internal/app/ec2/ec2.go
internal/app/ec2/ec2_test.go
internal/app/ec2/mock/ec2.go
internal/app/exporter/exporter.go

Add instance baseline
Many EC2 instances (e.g. t3 types) have a baseline and max value regarding `IOPS`, `throughput` and `bandwidth` EBS performances.
> 1 These instances can support maximum performance for 30 minutes at least once every 24 hours, after which they revert to their baseline performance.
> 2 These instances can sustain their stated performance indefinitely. If your workload requires sustained maximum performance for longer than 30 minutes, use one of these instances.
Since we don't collect baseline information, IOPS/throughput is massively over-evaluated for some instances (e.g. db.t3.small instances)'.
To make it easier to understand for end-user, we named it `burst` in dashboard's panels.
In this first iteration, I'm adding throughput information and reflect it in RDS …

Add instance baseline information

---

internal/app/exporter/exporter.go
internal/app/servicequotas/mock/servicequotas.go
internal/app/servicequotas/servicequotas.go
internal/app/servicequotas/servicequotas_test.go

This PR is fixing the bug faced in this issue https://github.com/qonto/prometheus-rds-exporter/issues/205
Until now if we failed to fetch some quota on AWS we ended up trying to log an error while the logger was `nil` which results in the application panicking
* Properly passing the logger to the `serviceQuotaFetch`
* Adding a aws.ToString to dereference string pointer to be safer
* Adding a new test case to pass in the problematic branch

Fix: Properly pass logger in ServiceQuota Fetcher

---

internal/app/servicequotas/servicequotas_test.go

This PR is adding a new line to pass the `wsl` rule of the linter.
This previous PR https://github.com/qonto/prometheus-rds-exporter/pull/209 broke the linter job
I've confirmed is working locally running:
```
golangci-lint run
```
Before and after the changes

fix: Update test to pass linter rules

---

README.md

When `serviceAccount.name` is not specified, the automatically generated `serviceAccount.name` will be inconsistent with the previously created role name, resulting in the following error:
```
can't fetch information about current session: operation error STS: GetCallerIdentity, get identity: get credentials: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, https response error StatusCode: 403
```

Fix missing set serviceAccount.name when deployed in EKS

---

internal/app/exporter/exporter.go

For aurora instances some expected instance values are missing. This makes some alert rules break with descriptions like "uses +Inf% of its disk IOPS" from https://github.com/qonto/database-monitoring-framework/blob/06895041d0c918915c24d4b30ed52049051d002c/charts/prometheus-rds-alerts/values.yaml#L125
This PR prevents the metrics I've identified as problematic from being exported when they have not been set.

fix: don't expose metrics with no values

---

CONTRIBUTING.md

Add depdency to run Helm unit tests
The [Helm unittest plugin](https://github.com/helm-unittest/helm-unittest) is required to run unit tests, but not yet documented in the contributing guide.
- Add Helm unittest plugin in the contributing guide

Add dependency to run Helm unit tests

---

configs/helm/templates/grafanadashboard.yaml
configs/helm/tests/grafanadashboard_test.yaml
configs/helm/tests/values/with_grafanadashboards_custom.yaml
configs/helm/values.yaml

Support deployment in non Grafana namespace
The Helm chart leverages the `GrafanaDashboard` CRD to deploy Grafana dashboards out of the box. However, in the current configuration, dashboards can only be imported into Grafana when the Prometheus RDS exporter and Grafana operator are deployed in the same namespace.
The [spec.allowCrossNamespaceImport](https://grafana.github.io/grafana-operator/docs/overview/#cross-namespace-grafana-instances) parameter in `GrafanaDashboard` CRD can be used to enabled cross-namespace dashboard import.
In fact, this should be the default value to support large variety of Kubernetes deployment, but be configurable for environment that requires strict isolation.
In this PR I'm adding the `allowCrossNamespaceImport`, with a default value to `true`
- Add …

Support deployment in non Grafana namespace

---

README.md
configs/aws/policy.json
configs/terraform/main.tf

Add missing IAM permissions for DB clusters
Current IAM permissions don't provides the `rds:DescribeDBClusters` DB permissions required since we added support of AWS DB clusters in 0.16.0, but the IAM permissions was not updated.
- Add `rds:DescribeDBClusters` IAM permission in IAM policies. According to AWS best practices, there are located in dedicated statement, with resource limited to rds clusters
It does not requires a release

Fix missing IAM permissions for DB clusters
